export const ADD_ALERT_START = 'ADD_ALERT_START';
export const ADD_ALERT_SUCCESS = 'ADD_ALERT_SUCCESS';
export const ADD_ALERT_FAILED = 'ADD_ALERT_FAILED';

export const DELETE_ALERT_START = 'DELETE_ALERT_START';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILED = 'DELETE_ALERT_FAILED';

export const GET_ALERT_START = 'GET_ALERT_START';
export const GET_ALERT_SUCCESS = 'GET_ALERT_SUCCESS';
export const GET_ALERT_FAILED = 'GET_ALERT_FAILED';

export const UPDATE_ALERT_START = 'UPDATE_ALERT_START';
export const UPDATE_ALERT_SUCCESS = 'UPDATE_ALERT_SUCCESS';
export const UPDATE_ALERT_FAILED = 'UPDATE_ALERT_FAILED';

export const GET_OPTIONS_START = 'GET_OPTIONS_START';
export const GET_OPTIONS_SUCCESS = 'GET_OPTIONS_SUCCESS';
export const GET_OPTIONS_FAILED = 'GET_OPTIONS_FAILED';

export const GET_CARD_START = 'GET_CARD_START';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILED = 'GET_CARD_FAILED';
